import {useEffect,useState} from 'react'; import {Link,Route,Routes,useNavigate} from 'react-router-dom'; import api from './api';

function Nav(){const nav=useNavigate();const user=JSON.parse(localStorage.getItem('user')||'null');return <nav><Link className="brand" to="/">LearnHub</Link><div><Link to="/courses">Courses</Link>{user&&<Link to="/dashboard">Dashboard</Link>}{user?.role==='INSTRUCTOR'&&<Link to="/instructor">Instructor</Link>}{user?<button onClick={()=>{localStorage.clear();nav('/login')}}>Logout</button>:<><Link to="/login">Login</Link><Link to="/register">Register</Link></>}</div></nav>}

function Home(){return <main className="hero"><div><small>ONLINE LEARNING SYSTEM</small><h1>Learn skills.<br/>Build your future.</h1><p>Discover courses, learn from structured lessons and track your progress in one place.</p><Link className="primary" to="/courses">Explore Courses</Link></div></main>}

function Auth({register=false}){const nav=useNavigate();const [f,setF]=useState(register?{username:'',email:'',password:'',role:'STUDENT'}:{username:'',password:''});const [err,setErr]=useState('');async function submit(e){e.preventDefault();try{const r=await api.post(register?'/auth/register':'/auth/login',f);localStorage.setItem('token',r.data.token);localStorage.setItem('user',JSON.stringify(r.data));nav('/dashboard')}catch(x){setErr(x.response?.data?.message||'Request failed')}}return <main className="auth"><form className="card form" onSubmit={submit}><h2>{register?'Create account':'Welcome back'}</h2><input placeholder="Username" value={f.username} onChange={e=>setF({...f,username:e.target.value})} required/>{register&&<input type="email" placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required/>}<input type="password" placeholder="Password" value={f.password} onChange={e=>setF({...f,password:e.target.value})} required/>{register&&<select value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option value="STUDENT">Student</option><option value="INSTRUCTOR">Instructor</option></select>}{err&&<p className="error">{err}</p>}<button className="primary">{register?'Register':'Login'}</button></form></main>}

function Courses(){const [cs,setCs]=useState([]),[q,setQ]=useState('');async function load(){setCs((await api.get('/courses',{params:q?{search:q}:{}})).data)}useEffect(()=>{load()},[]);async function enroll(id){const u=JSON.parse(localStorage.getItem('user')||'null');if(!u)return alert('Please login first');try{await api.post('/enrollments',{courseId:id});alert('Enrollment successful')}catch(e){alert(e.response?.data?.message||'Enrollment failed')}}return <main className="container"><div className="head"><div><small>LEARNING</small><h2>Explore Courses</h2></div><div><input placeholder="Search courses" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>Search</button></div></div><div className="grid">{cs.map(c=><article className="card" key={c.id}><span>{c.category||'General'}</span><h3>{c.title}</h3><p>{c.description}</p><p className="muted">Instructor: {c.instructor?.username}</p><button className="primary" onClick={()=>enroll(c.id)}>Enroll</button></article>)}</div>{!cs.length&&<p>No courses yet. Create one through the API as an instructor.</p>}</main>}

function Instructor(){const u=JSON.parse(localStorage.getItem('user')||'null');const [f,setF]=useState({title:'',description:'',category:''});const [msg,setMsg]=useState('');if(!u)return <main className="container"><h2>Please login.</h2></main>;async function create(e){e.preventDefault();try{await api.post('/courses',{...f,instructorId:u.userId});setMsg('Course created successfully');setF({title:'',description:'',category:''})}catch(x){setMsg(x.response?.data?.message||'Could not create course')}}return <main className="container"><small>INSTRUCTOR</small><h2>Create a Course</h2><form className="card form" onSubmit={create}><input placeholder="Course title" value={f.title} onChange={e=>setF({...f,title:e.target.value})} required/><input placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><textarea placeholder="Course description" value={f.description} onChange={e=>setF({...f,description:e.target.value})} rows="6" required/><button className="primary">Create Course</button>{msg&&<p>{msg}</p>}</form></main>}

function Dashboard(){const u=JSON.parse(localStorage.getItem('user')||'null');const [es,setEs]=useState([]);useEffect(()=>{if(u)api.get('/enrollments/student/'+u.userId).then(r=>setEs(r.data))},[]);if(!u)return <main className="container"><h2>Please login.</h2></main>;const avg=es.length?Math.round(es.reduce((a,e)=>a+e.progress,0)/es.length):0;return <main className="container"><small>DASHBOARD</small><h2>Hello, {u.username}</h2><p className="muted">Role: {u.role}</p><div className="grid"><article className="card"><h3>My Courses</h3><strong>{es.length}</strong></article><article className="card"><h3>Average Progress</h3><strong>{avg}%</strong></article></div><h3>Enrolled Courses</h3><div className="grid">{es.map(e=><article className="card" key={e.id}><h3>{e.course.title}</h3><p>{e.course.description}</p><progress value={e.progress} max="100"/><p>{e.progress}% complete</p></article>)}</div></main>}

export default function App(){return <><Nav/><Routes><Route path="/" element={<Home/>}/><Route path="/courses" element={<Courses/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/instructor" element={<Instructor/>}/></Routes></>}